### ISSUE TITLE
There are some errors when I run duo/gui/mian.py

### ISSUE THREAD

**Issue by xwt11** [3dqi/duo#1]
1. >The first error is 
Traceback (most recent call last):
  File "F:\Project\CT\duo-master\duo-master\duo\gui\gui.py", line 36, in run
    c = cai.Cai(dataPath, isToDumpIntermediateData = False)
TypeError: __init__() got an unexpected keyword argument 'isToDumpIntermediateData'
But I see there's no isToDumpIntermediateData in the cai.Cai function, so I've removed the isToDumpIntermediateData.

2. >But then the following error occurred
Traceback (most recent call last):
  File "F:\Project\CT\duo-master\duo-master\duo\gui\gui.py", line 36, in run
    c = cai.Cai(dataPath)
  File "F:\Project\CT\duo-master\duo-master\duo\zeff\cai.py", line 61, in __init__
    self.elementTable = com.elementTable
AttributeError: 'str' object has no attribute 'elementTable'

Can you help me with this problem? Thank you!

**Comment by kingcrimsontianyu** [comment]
Sorry the GUI part is dead code and should have been removed from this repo.
